#include "solvers/naive.hpp"
#include "solver_tests.hpp"

// TEST_SORTED_ADJ(solve_naive)
// TEST_SINGLE_NODE(solve_naive)
// TEST_SIMPLE(solve_naive)
// TEST_TRACK(solve_naive, 001)
// TEST_TRACK(solve_naive, 003)
// TEST_TRACK(solve_naive, 005)
// TEST_TRACK(solve_naive, 007)
// TEST_TRACK(solve_naive, 009)
// TEST_TRACK(solve_naive, 011)
// TEST_TRACK(solve_naive, 013)
// TEST_TRACK(solve_naive, 015)
// TEST_TRACK(solve_naive, 017)
// TEST_TRACK(solve_naive, 019)
// TEST_TRACK(solve_naive, 021)
// TEST_TRACK(solve_naive, 023)
// TEST_TRACK(solve_naive, 025)
// TEST_TRACK(solve_naive, 027)
// TEST_TRACK(solve_naive, 029)
// TEST_TRACK(solve_naive, 031)
// TEST_TRACK(solve_naive, 033)
// TEST_TRACK(solve_naive, 035)
// TEST_TRACK(solve_naive, 037)
// TEST_TRACK(solve_naive, 039)
// TEST_TRACK(solve_naive, 041)
// TEST_TRACK(solve_naive, 043)
// TEST_TRACK(solve_naive, 045)
// TEST_TRACK(solve_naive, 047)
// TEST_TRACK(solve_naive, 049)
// TEST_TRACK(solve_naive, 051)
// TEST_TRACK(solve_naive, 053)
// TEST_TRACK(solve_naive, 055)
// TEST_TRACK(solve_naive, 057)
// TEST_TRACK(solve_naive, 059)
// TEST_TRACK(solve_naive, 061)
// TEST_TRACK(solve_naive, 063)
// TEST_TRACK(solve_naive, 065)
// TEST_TRACK(solve_naive, 067)
// TEST_TRACK(solve_naive, 069)
// TEST_TRACK(solve_naive, 071)
// TEST_TRACK(solve_naive, 073)
// TEST_TRACK(solve_naive, 075)
// TEST_TRACK(solve_naive, 077)
// TEST_TRACK(solve_naive, 079)
// TEST_TRACK(solve_naive, 081)
// TEST_TRACK(solve_naive, 083)
