#include "solvers/reduce.hpp"
#include "solver_tests.hpp"

TEST_SORTED_ADJ(solve_reduce)
TEST_SINGLE_NODE(solve_reduce)
TEST_SIMPLE(solve_reduce)
TEST_TRACK(solve_reduce, 001)
TEST_TRACK(solve_reduce, 003)
TEST_TRACK(solve_reduce, 005)
TEST_TRACK(solve_reduce, 007)
TEST_TRACK(solve_reduce, 009)
TEST_TRACK(solve_reduce, 011)
TEST_TRACK(solve_reduce, 013)
TEST_TRACK(solve_reduce, 015)
TEST_TRACK(solve_reduce, 017)
TEST_TRACK(solve_reduce, 019)
TEST_TRACK(solve_reduce, 021)
TEST_TRACK(solve_reduce, 023)
TEST_TRACK(solve_reduce, 025)
TEST_TRACK(solve_reduce, 027)
TEST_TRACK(solve_reduce, 029)
TEST_TRACK(solve_reduce, 031)
TEST_TRACK(solve_reduce, 033)
TEST_TRACK(solve_reduce, 035)
// TEST_TRACK(solve_reduce, 037)
TEST_TRACK(solve_reduce, 039)
// TEST_TRACK(solve_reduce, 041)
TEST_TRACK(solve_reduce, 043)
// TEST_TRACK(solve_reduce, 045)
// TEST_TRACK(solve_reduce, 047)
TEST_TRACK(solve_reduce, 049)
// TEST_TRACK(solve_reduce, 051)
// TEST_TRACK(solve_reduce, 053)
// TEST_TRACK(solve_reduce, 055)
// TEST_TRACK(solve_reduce, 057)
// TEST_TRACK(solve_reduce, 059)
// TEST_TRACK(solve_reduce, 061)
// TEST_TRACK(solve_reduce, 063)
// TEST_TRACK(solve_reduce, 065)
// TEST_TRACK(solve_reduce, 067)
// TEST_TRACK(solve_reduce, 069)
// TEST_TRACK(solve_reduce, 071)
// TEST_TRACK(solve_reduce, 073)
// TEST_TRACK(solve_reduce, 075)
// TEST_TRACK(solve_reduce, 077)
// TEST_TRACK(solve_reduce, 079)
// TEST_TRACK(solve_reduce, 081)
// TEST_TRACK(solve_reduce, 083)
// TEST_TRACK(solve_reduce, 085)
// TEST_TRACK(solve_reduce, 087)
// TEST_TRACK(solve_reduce, 089)
// TEST_TRACK(solve_reduce, 091)
// TEST_TRACK(solve_reduce, 093)
// TEST_TRACK(solve_reduce, 095)
// TEST_TRACK(solve_reduce, 097)
// TEST_TRACK(solve_reduce, 099)
// TEST_TRACK(solve_reduce, 101)
// TEST_TRACK(solve_reduce, 103)
// TEST_TRACK(solve_reduce, 105)

// TEST_TRACK(solve_reduce, 113)
