name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          submodules: recursive

    - name: Installing Software
      run: |
        sudo apt update
        sudo apt install clang-format clang-tidy cmake ninja-build build-essential git -y

    - name: create build dir
      run: mkdir build

    - name: cmake
      working-directory: build
      run: cmake . -DCMAKE_BUILD_TYPE=Release -GNinja

    - name: ninja
      working-directory: build
      run: ninja

  # test:
  #   needs: build
  #   - name: test
  #     run: ctest -V -j