name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  windows:
    strategy:
      fail-fast: true
      matrix:
        build-type: [Debug, Release]

    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: ilammy/msvc-dev-cmd@v1

    - name: create build dir
      run: mkdir -p build

    - name: cmake
      run: cmake -S . -B build/ -G Ninja

  #   - name: build
  #     run: cmake --build build/ --config ${{ matrix.build-type }}
