name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          submodules: recursive

    - name: Installing Software
      run: |
        apt update
        apt install clang-format clang-tidy cmake ninja-build build-essential git -y

  build:
    needs: setup
    - name: cmake
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja

    - name: ninja
      run: ninja

  test:
    needs: build
    - name: test
      run: ctest -V -j