name: clang-format

on: push

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Install software
        run: sudo apt install clang-format -y
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Check formatting
        run: find fvs -iname *.hpp -o -iname *.cpp -o -iname *.h | xargs clang-format -style=file --dry-run --Werror
