name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          submodules: recursive

    - name: Installing Software
      run: |
        sudo apt update
        sudo apt install clang-format -y

    - name: clang-format
      run: find src -iname *.hpp -o -iname *.cpp -o -iname *.h | xargs clang-format -style=file --dry-run --Werror
