name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-ubuntu-release:
    runs-on: ubuntu-latest
    needs: build-ubuntu-release

    steps:
      - name: Download build files
        uses: actions/download-artifact@v3
        with:
          name: artifact-${{ runner.os }}-build-release
      
      - name: test
        working-directory: build
        run: ctest -V
